### PR TITLE
Features/data end time

### PR DESCRIPTION
**Pull request by pushpanjalip**
Fixes AB#362

- Determine length of video

- Create dynamic query for video end time

### CODE REVIEW

**Comment by kretep** [comment]
There are still two issues:

1. For the video of 6:12 min, the heatmap only shows until 5:44 min. This was working properly before. The query does seem to return the correct value though.

2. There seems to be a never ending cycle of aggregate_features queries being made. Perhaps some change in variable (this.endTime?) causes the apollo query to be executed over and over again, but I was unable to figure out why this happens exactly.

**Comment by bpmweel** [comment]
I made some changes to the way the queries are handled.

In general: Using refetch() is not a nice way to get data, you can use the results() callback in apollo to call functions that need to be updated.
Otherwise, you can assume that data will eventually be available as a variable that has the same name as the query in the apollo block.

For me there was an issue with the video flickering and reloading the page gave an error. Please check this pull request carefully.

**Comment by kretep** [comment]
The issue with the continuous refetching seems to be fixed now. But unfortunately, the heatmap still doesn't show the correct end time for me.

**Comment by kretep** [comment]
It seems the issue with the end time for the heatmap is a layout or cursor syncing issue. Let's see if it persists after the layout is reorganized.

**Pull request merged**
